version: '3.8'

services:
  prometheus:
    image: prom/prometheus:main
    container_name: prometheus
    ports:
      - '9090:9090'
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana:main
    container_name: grafana
    ports:
      - '3000:3000'
    restart: unless-stopped
    volumes:
      - ./grafana/datasources:/etc/grafana/provisioning/datasources
