apiVersion: v1
kind: PersidtentVolumeClaim
meatadata:
  name: {{ .Release.Name }}-mysql-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.mysqlVolume.persistentVolumeClaim.storageSize }}