replicaCount: 1

mysql:
  databaseName: spring_mysql_demo

springApp:
  image:
    repository: spring_mysql_demo
    pullPolicy: IfNotPresent
    tag: latest

mysqlVolume:
  persistentVolumeClaim:
    storageSize: 500Mi
  
  persistentVolume:
    storageSize: 500Mi
    pathOnHost: /var/lib/mysql

  mountPath: /var/lib/mysql