version: '3.8'

services:
  mysql:
    image: mysql:8.2.0-oracle
    container_name: spring-mysql-demo-db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - spring-mysql-network

  spring-mysql-demo:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring-mysql-demo-container
    depends_on:
      - mysql
    ports:
      - '8080:8080'
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/${MYSQL_DATABASE}?createDataBaseIfNotExist=true&characterEncoding=UTF-8&useUnicode=true&useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: ${MYSQL_USER}
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    networks:
      - spring-mysql-network

volumes:
  mysql_data:

networks:
  spring-mysql-network:
    driver: bridge
