version: '3.8'

services:
  mysql:
    image: mysql:8.2.0-oracle
    container_name: spring-mysql-demo-db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: spring_mysql_demo
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
