scrape_configs:
  - job_name: MyAppMetrics
    metrics_path: /actuator/prometheus
    scrape_interval: 5s
    static_configs:
      - targets: ['app-monitoring-spring-monitoring-demo-1:8080']
        labels:
          application: 'spring-prometheus-demo'